# Generated by Django 5.1.4 on 2025-01-21 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogKatalogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('status', models.TextField()),
            ],
            options={
                'verbose_name': 'Blog katalog',
                'verbose_name_plural': 'Blog kataloglar',
            },
        ),
        migrations.CreateModel(
            name='BlogMaxsulotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('narx', models.IntegerField(verbose_name='Blog katalog')),
                ('ombor', models.BooleanField(default=True, verbose_name='omborda mavjud')),
                ('kategorya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxsulotlar', to='blogs.blogkatalogmodel')),
            ],
            options={
                'verbose_name': 'Blog maxsulot',
                'verbose_name_plural': 'Blog maxsulotlar',
            },
        ),
    ]
