# Generated by Django 5.1.4 on 2025-01-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogkatalogmodel_blogmaxsulotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=265, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('massege', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
